# Generated by Django 5.1.1 on 2024-12-03 11:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.DecimalField(blank=True, decimal_places=1, max_digits=4, unique=True, validators=[django.core.validators.MinValueValidator(0.1)])),
            ],
        ),
        migrations.CreateModel(
            name='VehicleInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(blank=True, max_length=200)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('number', models.CharField(blank=True, max_length=15)),
                ('address', models.CharField(blank=True, max_length=1000)),
                ('vehicle_type', models.CharField(choices=[('', 'Select an option'), ('open', 'Open'), ('close', 'Close')], default='', max_length=10)),
                ('vehicle_number', models.CharField(max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z]{2}-\\d{2}-[A-Z]{2}-\\d{4}$', 'Enter a valid vehicle number (e.g., GJ-05-ES-9658)')])),
                ('capacity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MemberApp.vehiclecapacity')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles Info',
            },
        ),
    ]
