# Generated by Django 5.1.1 on 2024-11-16 13:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MemberApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclecapacity',
            name='capacity',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, unique=True, validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
    ]
