# Generated by Django 5.1.1 on 2024-11-14 07:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MemberApp', '0002_alter_vehiclecapacity_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclecapacity',
            name='capacity',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
    ]
